language: python
python:
  - "3.6"
  - "3.7"
dist: xenial
# setup environment
env:
  global:
    - DJANGO_SETTINGS_MODULE='MacPorts.settings'
    - DB_HOST=localhost
    - DB_PASSWORD=
    - DB_NAME=mp
    - DB_USER=postgres
    - SECRET_KEY=thISkEyisUsedForTravis
# install dependencies
install:
  - pip install -q -r app/requirements.txt
  - pip install codecov

# run test scripts
script:
  - python manage.py makemigrations --noinput
  - python manage.py migrate --noinput
  - python manage.py collectstatic --noinput
  - coverage run --source=. manage.py test
  - coverage report

services:
  - postgresql

before_script:
  - psql -c 'create database mp;' -U postgres
  - cd app

addons:
  postgresql: "10"

after_success:
  - codecov
